# Config for training only RSSM (no policy, etc.)
env:
  # Gym environment id used for training and evaluation
  name: CarRacing-v3
  # Spatial size images will be resized to before feeding the encoder
  image_size: 64
  # If true, convert renderings to single-channel grayscale
  grayscale: false
  eval_render_mode: rgb_array

model:
  # Encoder latent size (output dim of ConvEncoder)
  enc_latent_size: 256
  # Size of stochastic latent variable z
  stochastic_size: 32
  # Size of deterministic RNN hidden state
  deterministic_size: 128
  past_length: 3
  pred_length: 3
  output_uncertainty: false
  reward_size: 1

  conv_params:
    in_image_shape: [3, 64, 64]
    out_image_shape: [3, 64, 64]
    enc_kernel_size: 2
    dec_kernel_size: 2
    stride: 2
    pad: 1

loss:
  recon_mult: 1e3
  # KLD loss multiplier
  beta: 1e-5
  # KLD minimum clip value
  free_nats: 0.0
  kld_anneal_mode: linear
  image_loss: mse
  reward_mult: 1.0

training:
  seed: 0
  device: cuda:1
  epochs: 8000
  batch_size: 64
  learning_rate: 2e-4
  buffer_capacity: 2000
  updates_per_epoch: 5
  start_training_after: 5
  grad_clip: 100.0
  max_episode_steps: 200

evaluation:
  render_every_epochs: 100
  max_episode_steps: 200

checkpoint:
  run_root: runs
  save_every_epochs: 100
  final_weights_name: rssm_final.pt
  load_weights_path: null
